variables:
  GCP_ZONE: us-central1-a

stages:
  - go-install
  - lint
  - deploy

go-install:
  image: golang:1.13
  stage: go-install
  script:
    - go get
    - go mod vendor
  artifacts:
    paths:
      - vendor

lint:
  image: golangci/golangci-lint:v1.23.1
  stage: lint
  script:
    - golangci-lint run -v

deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION | base64 -d > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud functions deploy HelloHTTP --runtime go111 --trigger-http --entry-point HelloHTTP --project shinofara-233410