version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 127.0.0.1:53306:3306
    hostname: db

  init:
    image: mysql:5.7
    volumes:
      - ./db:/work
    working_dir: /work
    depends_on:
      - db
    command:
      - ./init.sh
